apiVersion: v1
kind: ConfigMap
metadata:
  name: portfolio-config
data:
  STUDENT_NAME: "Mohammad Siddiqi"
  GITHUB_USERNAME: "almsid"
  GITHUB_REPO: "devsecops-portfolio-template"
  BIO: "DevOps engineer building secure, automated infrastructure."
  VAULT_ADDR: "http://vault.default:8200"
  VAULT_SECRET_PATH: "secret/data/github-app"
  # LINKEDIN_URL: ""
  # WEBSITE_URL: ""
