apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- configmap.yaml

images:
- name: ghcr.io/almsid/devsecops-portfolio-template
  newName: ghcr.io/almsid/devsecops-portfolio-template
  newTag: sha-f811f41
